### ISSUE TITLE
br tag being inserted after final unordered list item

### ISSUE THREAD

**Issue by dmagoo** [textile/php-textile#177] opened 2017-07-17 20:54 UTC
Tis can be reproduced as follows:

```php
$input = "
*This is my header*
* here is an item
* and another";

echo textile($input);
```

Output:
```html
<p><strong>This is my header</strong><br />
  <ul>
    <li>here is an item</li>
    <li>and another</li><br />
  </ul></p>


```

**Comment by eliph** [comment] 2017-08-27 19:25
*This is my header*

* here is an item
* and another";

**Comment by netcarver** [comment] 2017-09-28 08:51
As eliph said. This is currently a limitation in php textile as the list block needs to be separated from the preceding block. This is a duplicate of  #22 so closing this issue.

**Closed by netcarver** 2017-09-28 08:51 UTC

**Comment by dmagoo** [comment] 2017-09-29 18:31
Fair enough, but it isn't a dupe of #22.  That issue concerns the enclosing p tag.  This issue involves a br tag that is inserted into an unordered list, outside, of an li tag.
