### ISSUE TITLE
Parsing links results in fatal error

### ISSUE THREAD

**Issue by wpalchemist** [textile/php-textile#222] opened 2023-01-07 18:41 UTC
### Prerequisites

* [x] Are you running the latest version of PHP-Textile?
* [ ] `$ composer update`?

### Expected behaviour
```
$this->textile = new \Netcarver\Textile\Parser();
echo $this->textile->parse( '"Google":http://google.com' );
```
should result in 
```
<a href="http://google.com">Google</a>
```

### Actual behaviour

Fatal error:
```
[Mon Jan 02 12:12:06.330674 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class "Netcarver\\Textile\\Tag" not found in <url>/vendor/textile/src/Netcarver/Textile/Parser.php:2444, referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330858 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: Stack trace:, referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330871 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #0 <url>/vendor/textile/src/Netcarver/Textile/Parser.php(4422): Netcarver\\Textile\\Parser->newTag('a', Array, false), referer: <url>authors.php?search=chaucer
[Mon Jan 02 12:12:06.330879 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #1 [internal function]: Netcarver\\Textile\\Parser->fLink(Array), referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330887 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #2 <url>/vendor/textile/src/Netcarver/Textile/Parser.php(4204): preg_replace_callback('/\\n             ...', Array, 'textileRef:1730...'), referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330895 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #3 <url>/vendor/textile/src/Netcarver/Textile/Parser.php(4069): Netcarver\\Textile\\Parser->replaceLinks('textileRef:1730...'), referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330903 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #4 <url>/vendor/textile/src/Netcarver/Textile/Parser.php(3567): Netcarver\\Textile\\Parser->links('textileRef:1730...'), referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330910 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #5 <url>/vendor/textile/src/Netcarver/Textile/Parser.php(3449): Netcarver\\Textile\\Parser->graf('"Google":http:/...'), referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330936 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #6 <url>/vendor/textile/src/Netcarver/Textile/Parser.php(3298): Netcarver\\Textile\\Parser->fBlock(Array), referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330966 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #7 <url>/vendor/textile/src/Netcarver/Textile/Parser.php(1963): Netcarver\\Textile\\Parser->blocks('"Google":http:/...'), referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330975 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #8 <url>/class-authors.php(275): Netcarver\\Textile\\Parser->parse('"Google":http:/...'), referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330983 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #9 <url>authors.php(9): OMSB\\Authors->display_author('233'), referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330991 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr: #10 {main}, referer: <url>/authors.php?search=chaucer
[Mon Jan 02 12:12:06.330998 2023] [fcgid:warn] [pid 11116] [client 76.22.0.85:55565] mod_fcgid: stderr:   thrown in <url>/vendor/textile/src/Netcarver/Textile/Parser.php on line 2444, referer: <url>/authors.php?search=chaucer
```

Links are the only tags that have this problem: all other formatting gets parsed correctly. 

### Steps to reproduce

```
$this->textile = new \Netcarver\Textile\Parser();
echo $this->textile->parse( '"Google":http://google.com' );
```

#### Additional information

PHP-Textile version: 4.0.0
PHP version: 8.0

**Comment by gocom** [comment] 2023-01-08 11:11
Appears that the `\Netcarver\Textile\Tag` class can not be loaded, or resolved by PHP. Commonly this would be caused by missing PSR-4 autoloader.

Make sure the library is installed through Composer, and that Composer's autoloader (or other PSR-4 autoloader) is included before trying to use the parser. An autoloader is required so that PHP is able to resolve classes without manually requiring files.

I'll be closing this issues as invalid, but if you have additional questions or need help, don't be discouraged to ask.

**Closed by gocom** 2023-01-08 11:11 UTC

**Comment by wpalchemist** [comment] 2023-01-21 17:18
Thank you, @gocom!  I am going to be using this on a server that isn't running composer, so I was trying to use it without composer.  Adding the autoloader fixed the problem.  Thanks for your help!
